# Site settings
title: Arcturus Robotics
description: A student-led robotics team competing in the First Tech Challenge.
author:
  name: Arcturus Robotics
  email: ftcarcturus13245@gmail.com
  social:
    instagram: arcturusrobotics
    github: arcturus-robotics
    rss: Arcturus Robotics
    youtube:
      id: UC_kJwWS4xiON9qoONGbpC4g
      name: Arcturus Robotics
keywords:
  - Arcturus
  - Robotics
  - Arcturus Robotics
  - First Tech Challenge
  - Engineering
  - Programming
  - Business
  - Outreach

# Build settings
markdown: kramdown
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - scripts
  - config.codekit3
plugins:
  - jekyll-feed
  - jekyll-seo-tag
